"""SQLite 下的自增主键必须真的能自增（E26）。

起因是 E18 记下的那对矛盾：同一份 metadata，`prompt_trace` / `tb_user` 通过 fixture 的
`db_session` 插得进去、通过 app 的 `SessionLocal` 插就撞
`IntegrityError: NOT NULL constraint failed: <table>.id`。当时写成"未解释、不当已修"。

答案在 `backend/conftest.py`：它把 `DATABASE_URL` 设成 `sqlite://` 后立刻
`Base.metadata.create_all(bind=_app_engine)`，而**把 `BigInteger` 渲染成 `INTEGER` 的那条
`@compiles` 钩子注册在这次建表之后**。SQLite 只有 `INTEGER PRIMARY KEY` 才是 rowid 别名，
所以那 46 张表的 `id` 全是字面 `BIGINT NOT NULL` —— 不给 id 就必然违反 NOT NULL。
钩子注册之后跑的 `create_all`（fixture 那块库）拿到的是 `INTEGER`，于是"一边插得进一边插不进"。

这里钉两件事：那块库的 DDL 形状，以及真的能不给 id 插进去。
"""

from __future__ import annotations

from sqlalchemy import inspect, text

from app.core.database import SessionLocal
from app.core.database import engine as app_engine
from app.core.security import hash_password
from app.models.user import User

# 模型清一色 BigInteger 主键（46 张表 / 0 张 Integer），所以这几张就够代表全部。
TABLES_WITH_BIGINT_PK = ("tb_user", "prompt_trace", "agent_task")


def _id_column_line(table: str) -> str:
    with app_engine.connect() as conn:
        ddl = conn.execute(text(f"SELECT sql FROM sqlite_master WHERE type='table' AND name='{table}'")).scalar()
    assert ddl, f"{table} 没建出来 —— app 引擎那块共享库是空的？"
    return next((line.strip() for line in ddl.splitlines() if line.strip().lower().startswith("id ")), ddl[:80])


def test_bigint_primary_keys_render_as_rowid_aliases():
    bad = {table: _id_column_line(table) for table in TABLES_WITH_BIGINT_PK}
    wrong = {table: line for table, line in bad.items() if not line.lower().startswith("id integer")}
    assert not wrong, (
        "这些表的 id 不是 INTEGER —— SQLite 下它就不是 rowid 别名、不会自增。"
        "`conftest` 的 @compiles(BigInteger, 'sqlite') 必须注册在任何 create_all 之前：" + str(wrong)
    )


def test_an_insert_without_an_id_gets_an_autogenerated_one():
    """正面证明：不给 id 也插得进去（这就是原来炸掉审计行的那一列）。"""
    session = SessionLocal()
    try:
        user = User(username="autoid-probe", email="autoid-probe@x.io", password=hash_password("ProbePass123!"))
        session.add(user)
        session.commit()
        assert user.id and user.id > 0, f"没拿到自增主键：{user.id!r}"
    finally:
        session.rollback()
        session.close()


def test_the_app_engine_actually_has_the_full_schema():
    """防空转：真在那块库里看到了几十张表，而不是因为库是空的所以"没有 BIGINT 列"。"""
    tables = set(inspect(app_engine).get_table_names())
    assert len(tables) >= 40, f"app 引擎那块库里只有 {len(tables)} 张表"
    assert set(TABLES_WITH_BIGINT_PK) <= tables
